"""empty message

Revision ID: 1b3554379c5d
Revises: debaa9402d9d
Create Date: 2024-11-23 04:25:37.399093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3554379c5d'
down_revision = 'debaa9402d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history_updated',
    sa.Column('session_id', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('faculty_name', sa.String(), nullable=False),
    sa.Column('chats', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('session_id', 'faculty_name')
    )
    op.drop_table('chat_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('session_id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('chats', sa.VARCHAR(), nullable=False),
    sa.Column('faculty_name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.drop_table('chat_history_updated')
    # ### end Alembic commands ###
